### ISSUE TITLE
Doesn't always load.

### ISSUE THREAD

**Issue by WuhbGaming** [cleanlock/Partyframe-Pets-Fix#1]
Needs to trigger automatically on a new instance, zone change, or party change.

**Comment by muleyo** [comment]
`GROUP_ROSTER_UPDATE`

It should update whenever your groupsize changes (member leaves/joins). When exactly do you have issues?

**Comment by WuhbGaming** [comment]
If group size doesn't change after I leave an instance or an arena it will default to normal settings.

**Comment by muleyo** [comment]
I'll look into it and push an update.

**Comment by WuhbGaming** [comment]
Sorry I just realized I'm posting this in wrong tab.

was intended for https://github.com/cleanlock/PartyRaidFrameResize
but thanks for the addon and effort you're putting in it.

**Comment by muleyo** [comment]
No worries :) I'll merge it into the correct repo.
